### ISSUE TITLE
First elmish state update discarded

### ISSUE THREAD

**Issue by omcnoe** [slaveOftime/Fun.Blazor#25]
The first state update is discarded, unless you use the `html.elmish` constructor that includes an initial `Cmd<Msg>`, AND the `Msg` is not a noop.

`Fun.Blazor.Wasm 2.0.0-beta008`

Simple repro:
```
type State =
    { Count: int }
    static member init = { Count = 0 }

type Msg = SetCount of int

let update msg state =
    match msg with
    | SetCount count -> { state with Count = count }, Cmd.none

let render state (dispatch: Msg -> unit) =
    Template.html
        $"""
        <div>
            {state.Count} <button onclick={fun _ -> SetCount(state.Count + 1) |> dispatch}>+</button>
        </div>"""

let app =
    html.elmish ((fun _ -> State.init, Cmd.none), update, render)
```

**Comment by albertwoo** [comment]
@omcnoe you should add package Fun.Blazor.Elmish.

**Comment by omcnoe** [comment]
I have all the necesary packages in the .fsproj
```
<PackageReference Include="Fun.Blazor.Elmish" Version="2.0.0-beta*" />
 <PackageReference Include="Fun.Blazor.HtmlTemplate" Version="2.0.0-beta008" />
 <PackageReference Include="Fun.Blazor.Wasm" Version="2.0.0-beta*" />
```
And my code does open the necessary modules. Sorry just got cropped out of the example.

I think it is an actual bug if init Cmd is `Cmd.none` :) Understood that project is in beta.

**Comment by albertwoo** [comment]
Sorry I misunderstanded your point. I can reproduce that now.
It is here: https://github.com/slaveOftime/Fun.Blazor/blob/29068b94fae0974323399ae116c4b729c24e4244/Fun.Blazor.Elmish/ElmComponent.fs#L31-L44
I will check how elmish work again and try to fix it. If you are very familiar with elmish your help will be very welcomed :)

**Comment by albertwoo** [comment]
@omcnoe hi, I changed the init a little bit. The bug should be fixed.

But I will lerarn more on elmish to improve it when I got more time.

**Comment by omcnoe** [comment]
Yes, issue is fixed. Thanks.
