### ISSUE TITLE
[Question] - Async Lifecycle events

### ISSUE THREAD

**Issue by AngelMunoz** [slaveOftime/Fun.Blazor#3]
I noticed that you can access some of the life cycle events inside thanks to `IComponentHook` interface
is it safe to do async operations inside these events?

I was planning to do something like

```fsharp
      hook.OnFirstAfterRender.Subscribe (fun () ->
        myTask()
        |> Async.AwaitTask
        |> Async.Start
      )
      |> hook.AddDispose
```

Also I don't seem to be able to grab `OnInitialized` event anywhere

**Comment by albertwoo** [comment]
Before I normally convert myTask to Observerble, so when the data is ready I can put it into some local store
```fsharp
let data = cval(...)

hook.OnFirstAfterRender.Add (fun () ->
        myTask()
        |> Observerble.ofTask
        |> Observerble.subscribe data.Publish
        |> hook.AddDispose
)
```

For other lifecycle event like OnInitialized can be added in the future when I got time. It is in https://github.com/slaveOftime/Fun.Blazor/blob/master/Fun.Blazor/DIComponent.fs

Yes, to support async directly in the hook can be a good feature like you can do in C#.

**Comment by AngelMunoz** [comment]
That is something I had not consider I will use that pattern thanks!
