### ISSUE TITLE
CE style vs Feliz style

### ISSUE THREAD

**Issue by nr-4** [slaveOftime/Fun.Blazor#32]
I know CE style is quicker than Feliz style, but how do you figure out which properties exist for a type with CE style?

the tooltip says nothing, the recommendations are crowded

![image](https://user-images.githubusercontent.com/36763595/155858698-351e7799-9078-4bc4-8115-875d2b399369.png)

![image](https://user-images.githubusercontent.com/36763595/155858643-085c8642-2ead-4f90-9f37-6e99d5e8e68f.png)

is it maybe possible to add the properties as xml documentation for the type or.. is there a way that i don't know of?
of course i could check the generated bindings but this would be very slow

so i was hoping maybe you've got a solution for this

**Comment by albertwoo** [comment]
Yeah, the intellisense it not that good.
In your second screen, after you input the first "property", then you can get intellisense for other ones. At least it works in VS.

**Comment by albertwoo** [comment]
![image](https://user-images.githubusercontent.com/8017681/155904865-9f6b31c9-fe6b-420e-8462-bcb5387729a2.png)

**Comment by albertwoo** [comment]
You can even filter by methods:
![image](https://user-images.githubusercontent.com/8017681/155905159-19f8b9cd-f8c0-4830-9df1-d2c2912c238b.png)

**Comment by jkone27** [comment]
i am also a big fan of list comprehension over custom CE, more like Feliz style, as F# is the only language allowing higher order function of list without ; for separation making it quite sweet, would also a non-CE way of representing / building pages be possible / available? like using Feliz.ViewEngine or similar? cheers

**Comment by albertwoo** [comment]
Currently, I have no plan to support list/feliz style.
