### ISSUE TITLE
How to use the SnackBar?

### ISSUE THREAD

**Issue by rabejens** [slaveOftime/Fun.Blazor#33]
I found a `MudSnackBarProvider'` which I added in my `view` function. Now, how do I post things to the SnackBar when an event happens? Do I have to get an `ISnackBar` via `html.inject` and hand it down through my `view` functions or is there a more Fun.Blazorish way?

**Comment by albertwoo** [comment]
I normally just use html.inject to wrap every components which need services like ISnackBar, IComponentHook etc.

**Comment by rabejens** [comment]
I did it this style. I added `MudSnackbarProvider'` and injected an `ISnackbar`. Then, I prepare functions posting my desired mesages to the snackbar beforehand, prepare `update` functions with these as parameters and use `Cmd.OfFunc.attempt` to call them.

Example:

```fsharp
let update reportOnSnackbar msg state =
    match msg with
    | AddFiles files ->
        let filesToAdd = files |> Seq.filter(fun f -> state.files |> List.contains f |> not) |> Seq.toList
        let cmd = Cmd.OfFunc.attempt reportOnSnackbar (sprintf "%d file%s added" filesToAdd.Length (if filesToAdd.Length = 1 then "" else "s")) Failed
        { state with files = List.append filesToAdd state.files }, cmd
    // more...
```
