### ISSUE TITLE
Docs Broken

### ISSUE THREAD

**Issue by AngelMunoz** [slaveOftime/Fun.Blazor#37]
Looks like the docs are broken the side drawer opens and closes but the content of the pages looks empty

![image](https://user-images.githubusercontent.com/8684875/169919339-06263c5d-bc87-4ae0-8832-d22188ba5be8.png)

**Comment by albertwoo** [comment]
No, server side blazor is removed because my cloud virtual machine is going to be expired. Please use the wasm mode docs.

**Comment by albertwoo** [comment]
Error handling is added. But server mode docs is not update. Because it is going to be erased in recent days. 

Will close this one.
