### ISSUE TITLE
dotnet templates

### ISSUE THREAD

**Issue by AngelMunoz** [slaveOftime/Fun.Blazor#4]
It would be nice to have a couple of dotnet templates

I mainly care for wasm bolero, but I guess other might want server bolero/blazor

If I have a chance during the week I'll try to get you a PR

**Comment by albertwoo** [comment]
I made a repo for couple of simple usecases: https://github.com/slaveOftime/Fun.Blazor.Samples
Those can be treated as templates.

Yes if we have cli templates, it will be better.

**Comment by AngelMunoz** [comment]
Hey hope all is well, have you had a change to take a look at 
https://github.com/slaveOftime/Fun.Blazor.Samples/pull/1 ?

**Comment by albertwoo** [comment]
Sorry, I did not noticed the email for that. I will take a look in the next few days.

**Comment by albertwoo** [comment]
@AngelMunoz thanks for your work!!! 👍
It is now merged. Github actions also setup for it. It is now published on nuget.
