### ISSUE TITLE
Support for Blazor WASM debugging

### ISSUE THREAD

**Issue by boyedarat** [slaveOftime/Fun.Blazor#44]
@albertwoo FsBolero has support for WebAssembly debugging in VS using Chrome-devtools:
https://github.com/fsbolero/Bolero/issues/294
https://github.com/fsbolero/Bolero/issues/307

Would it be possible to do something similar with Fun.Blazor?

Thanks.

**Comment by albertwoo** [comment]
I think it just works for Fun.Blazor wasm, you just need to add 

```
"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}"
```

into your **launchSettings.json**.
I also updated the templates: **dotnet new install Fun.Blazor.Templates::3.0.3**

**Comment by boyedarat** [comment]
Can't get it to work on VS Code though:
`info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Fallback /wasm'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost/wasm - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Fallback /wasm'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'Fallback /wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost/wasm - -
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'Fallback /wasm'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Fallback /wasm'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 GET http://localhost/wasm - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Fallback /wasm'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'Fallback /wasm'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Fallback /wasm'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost/wasm - - - 200 - text/html;+charset=UTF-8 16.2767ms
The program '[11840] BlazorTest.Server.dll' has exited with code -1 (0xffffffff).`

Here is the `launch.json` that was used:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "blazorwasm",
            "name": "Launch and Debug Blazor WebAssembly Application",
            "request": "launch",
            "browser": "edge",
            "hosted": true,
            "program": "${workspaceFolder}/BlazorTest.Server/bin/Debug/net7.0/BlazorTest.Server.dll",
            "cwd": "${workspaceFolder}/BlazorTest.Server",
            "url": "http://localhost:5000"
        }
    ]
}`

Works fine on FsBolero though.

**Comment by albertwoo** [comment]
Are you using mix mode template. If so, it may not work. I only tried pure WASM mode. And only updated pure WASM mode template. And I only tried on VS for Windows.

**Comment by albertwoo** [comment]
Today, I also tried the latest pure WASM template in VSCode, the generated default launch.json is working fine with the debug too:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch and Debug Standalone Blazor WebAssembly App",
            "type": "blazorwasm",
            "request": "launch",
            "cwd": "${workspaceFolder}"
        }
    ]
}
```
