### ISSUE TITLE
[Fun.Blazor.CustomElements] preRenderNode does not get replaced by Custom Element

### ISSUE THREAD

**Issue by poroburu** [slaveOftime/Fun.Blazor#45]
# Issue
`index.fs` in [GiraffeHtmxBlazor](https://github.com/albertwoo/GiraffeHtmxBlazor)
* `preRenderNode` does not get replaced by Custom Element. Instead it appends the Custom Element.

```fsharp
html.customElement<StocksView>(preRenderNode = div {
                        "Loading stocks ..."
                        progress { class' "progress h-2" }
                    })
```

* `html.customElement<StocksView>(preRender = true)` load also duplicates in the htmx trigger `hxGet "view/stocks"`. The first element is static. The second element correctly handles the `AddFirstAfterRenderTask` effect.

# Reproduce:
Following along from 
https://github.com/albertwoo/GiraffeHtmxBlazor
in
https://www.slaveoftime.fun/blog/mix-giraffe,-htmx-and-blazor-together

Upgrade package from 
`<PackageReference Include="Fun.Blazor.CustomElements" Version="3.0.0-beta004" />`
to
`<PackageReference Include="Fun.Blazor.CustomElements" Version="3.0.0" />`
surfaces issue. Breaks in 
`<PackageReference Include="Fun.Blazor.CustomElements" Version="3.0.0-beta007" />`

**Comment by albertwoo** [comment]
@poroburu I updated repo https://github.com/albertwoo/GiraffeHtmxBlazor, please sync and try again.
