### ISSUE TITLE
Question: Proper way to handle lists in adaptiview

### ISSUE THREAD

**Issue by mathantunes** [slaveOftime/Fun.Blazor#50]
I want to build a form with a list of a given property and therefore I'm experimenting with `adaptiview` and lists.

Based on the sample counter, I managed to come up with the following:

```fsharp
let app =
    adaptiview () {
        let! li, setLi = cval<string list>([]).WithSetter()
        let listView = li |> List.map (fun l -> div { l })

        div {
            div {
                yield! listView
            }

            button {
                onclick (fun _ -> transact(fun _ ->  setLi(li @ [ "New row" ])))
                "Append"
            }
        }
    }
```

The snippet above works. The UI refreshes as expected 🙌 .

But also, there's a type [clist](https://fsprojects.github.io/FSharp.Data.Adaptive/reference/fsharp-data-adaptive-clist-1.html) which seems more convenient for this but then a `let! values = clist(["initial"])` can't be bound using `let!`.

What I imagined I would be able to do here is something like:

```fsharp
let app =
    adaptiview () {
        let! li = clist([])
        let listView = li |> List.map (fun l -> div { l })

        div {
            div {
                yield! listView
            }

            button {
                onclick (fun _ -> transact(fun _ ->  li.Append([ "New row" ])))
                "Append"
            }
        }
    }
```

Is this something that just isn't supported at the moment? Or am I doing something off? 😅 

Thanks for the support!

**Comment by albertwoo** [comment]
Hi @mathantunes , **adaptiview** is only support binding cval and aval. You can just convert clist to cval right?

**Comment by albertwoo** [comment]
Or just write something like below. Blazor's diff is good enough, we do not need to use clist to introduce more complexisty. **adaptiview** is just to create a area to narrow down the dynamic area, so blazor can calculate less when doing diff.

```fsharp
let app =
    adaptiview () {
        let! items, setItems = cval<string list>([]).WithSetter()
        
        let listView = 
            items 
            |> List.map (fun item -> div { 
                key item // use blazor diff for better performance instead of clist
                item 
            })

        div {
            div {
                yield! listView
            }
            button {
                onclick (fun _ -> 
                    [ "New row" + Random.Shared.Next().ToString() ] 
                    |> List.append items
                    |> setItems
                )
                "Append"
            }
        }
    }
```

**Comment by mathantunes** [comment]
The cval approach looks good to me.

Thank you for the support, @albertwoo.
