### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by AngelMunoz** [slaveOftime/Fun.Blazor#53]
Hey if you don't mind, I'd like to start sending out some PRs to either update/add some of the documentation.

For what I've been doing this week I'd like to polish the following parts

- DOM and Move region content into the DOM parts.
  
  I'd like to center a bit more on three particular topics: elements, attributes, and events. I'd like to also include the region explanation right where we have a heading called "dynamic content" so we don't need to visit two places before figuring out what are the component parts. I'd also like to move the StyleBuilder examples to the Style document just for consistency. An introduction to FSharp.Data.Adaptive here would also be ideal as it would serve to guide users into adaptive programming.

- Classes vs Functions.

  Here I'd like to make the distinction about when to use just classes and when just functions, many F# folks don't like the idea of classes and if there are classes examples in the documentation, they might get the idea that classes are required to work when they're mostly not.

- Plain Blazor and F# 

  I think this is in the FAQ but I believe this is an important bit of information it should have its own section about how to interoperate with plain blazor components from F# and how to make F# components that can be consumed from blazor.

- Remove the MudBlazor mentions in the documentation examples and explain how to add bindings to other libraries.

  I think MudBlazor is a fine library but for folks outside of the blazor community it can be hard to understand what `MudTable'()` is and where does it come from, I think bindings by themselves require their own section to explain what they are and how to consume them, the rest of the documentation should have plain html/blazor dsl only to avoid confusion.

- List the family of libraries in the first page (Fun.Blazor.Reactive, Fun.Blazor.Elmish, etc etc)

  I think this is important for other users just to know what they can have out of the box with Fun.Blazor while the current documentation has some information about that, it doesn't really mention that there are packages part of the Fun.Blazor family so it would be nice if those were discoverable on the landing page of the docs.
- Routing Blazor-like vs Giraffe-like

  Add a little bit more of information of when and why you'd like to blazor-like/giraffe-like and if there are any downsides to any of those approaches

That's some of the feedback I could gather this week that I've been using Fun.Blazor a little bit more.

Please, let me know if this sits well with you or if you'd like to take a different approach.

**Comment by albertwoo** [comment]
@AngelMunoz thanks for your time and contribute. All those topics makes sense tome.

For PR https://github.com/slaveOftime/Fun.Blazor/pull/54, I added some comments. Just do not want to freak people out at the beginning 😂
