### ISSUE TITLE
Example for Bindings?

### ISSUE THREAD

**Issue by EHotwagner** [slaveOftime/Fun.Blazor#56]
Hi, is there an up to date example of how to use Bindings around?
There seems to be some plumbing necessary to get it to work.

**Comment by albertwoo** [comment]
If you are pointing things to https://slaveoftime.github.io/Fun.Blazor.Docs/Docs/Bindings, then you just need to follow related third party package's document. For example, if you want to use MudBlazor:
- Create a project with Fun.Blazor.Templates
- Add Fun.Blazor.MudBlazor
- Go to MudBlazor document, follow their instructions, use Fun.Blazor DSL for their csharp razor example.

All the bindings will append **'** to the original component, for example: MudButton would be MudButton'.

You can also check the Fun.Blazor.Docs app as the example: https://github.com/slaveOftime/Fun.Blazor/blob/master/Fun.Blazor.Docs.Wasm/App.fs

**Comment by EHotwagner** [comment]
Ah, sure. It was my bad. I still had an older template where the folder structure was a little different.

**Comment by albertwoo** [comment]
@EHotwagner here is a sample repo: https://github.com/slaveOftime/Fun.Blazor.Samples/tree/main/samples/FunWasm.MudBlazorDemo
