### ISSUE TITLE
real time communication

### ISSUE THREAD

**Issue by EHotwagner** [slaveOftime/Fun.Blazor#57]
What are practical ways for real time communication between server and clients?

- I got grpc working without problems but protobuf is rather cumbersome for experimenting around. 
- SignalR would be the obvious alternative but vanilla or something like https://github.com/ArtemyB/Fable.SignalR/tree/net6  
- There is of course also Elmish.Bridge but I would prefer to avoid Elmish.

**Comment by albertwoo** [comment]
Fun.Blazor has no opinon on thic topic. But if you are using server mode blazor, then you already got the real time communication feature. For wasm mode, I also have no experience.

**Comment by EHotwagner** [comment]
Yes, I am interested in wasm mode and hoped I might have missed some better innate Blazor feature.  
FYI: https://github.com/Arshia001/FSharp.GrpcCodeGenerator works without any problems.
