### ISSUE TITLE
example of mudblazor

### ISSUE THREAD

**Issue by yuuuxt** [slaveOftime/Fun.Blazor#58]
Having a complete MudBlazor (blazor) project sample would be good.

For example, trying to write `<MudMainContent>@Body</MudMainContent>` like `MudMainContent'() { this.Body }` throws error, while `main { this.Body }` is valid.

**Comment by albertwoo** [comment]
In the future we will provide some samples.

For the MudMainContent, yes current it is invalid, because **this.Body** is blazor raw renderfragment, and for component we did not provide yield overload for it. but you can still write it like:

```fsharp
MudMainContent'() { html.renderFragment this.Body }
```

**Comment by albertwoo** [comment]
When you update Fun.Blazor to 4.0.4, **MudMainContent'() { this.Body }** should be valid.

**Comment by yuuuxt** [comment]
Thanks for the quick fix! Tried and still stuck on the `layouts` page of `mudblazor` doc. look forward to the upcoming samples :)

**Comment by albertwoo** [comment]
I am using fun-blazor template, it is for SSR, server, wasm at the same time. So the MainLayout cannot be interactive in simple way.

I added a demo in the templates repo, and here is the commit for adding MudBlazor: https://github.com/slaveOftime/Fun.Blazor.Samples/commit/5e1b196fc3344bffa9be2a8c4a1cc508a20110b3

**Comment by yuuuxt** [comment]
Also, could you cover the usage of [Snackbar](https://mudblazor.com/components/snackbar#usage)? Thanks!

**Comment by albertwoo** [comment]
Here is the commit for it: https://github.com/slaveOftime/Fun.Blazor.Samples/commit/97fd24a6e0471b9790e89c5422e8803c51d731dd

I assume you are using the **fun-blazor** template which is contains a lot of concept, like SSR, navigation enhancement, server side interactive and wasm interactive etc. By default the whole app is static, so the snackbar is not working  by default. I recommend you to check wasm sample: https://github.com/slaveOftime/Fun.Blazor.Samples/tree/main/samples/FunWasm.MudBlazorDemo

**Comment by yuuuxt** [comment]
just tried the wasm demo, it's working except the navigation between 2 pages. Am I doing anything wrong?

![temp](https://github.com/slaveOftime/Fun.Blazor/assets/3153534/b845ff55-5c91-409c-81a7-228469ea3a35)

**Comment by albertwoo** [comment]
Can you show me your code?

**Comment by yuuuxt** [comment]
The code is not available right now, but it was a simple copy of the sample counter page (after splitting pages into separate files), and the router and the link were simple copies as well ( another row of `routeCi "/check" checkPage` and another `MudNavLink`)

Do you also mean it's not reproduced (yet) on your side?

**Comment by albertwoo** [comment]
Not reproduced so far.

**Comment by yuuuxt** [comment]
OK, will try it again after work. Thanks for the quick feedback!

**Comment by yuuuxt** [comment]
this repo can reproduce the gif shown above for me: https://github.com/yuuuxt/BlazorWasmSample

**Comment by albertwoo** [comment]
@yuuuxt sorry, it is my bad, I should not use **html.injectWithNoKey** for pages, because in that way, if two pages use it, then when Blazor try to rerender and will treat them as same component, and will not re-create it.

But with **html.inject**, by default it will create a random key, so it will always create a new component. You can check the doc for more: https://slaveoftime.github.io/Fun.Blazor.Docs/Docs/Advanced-features/Dependency-injection-(DI)

I also improved **html.route** in 4.0.5 to cover this kind of use cases.

The recommendation is to use **html.inject** with random key or specified key for this kind of cases.
