### ISSUE TITLE
Support collections in adaptiview

### ISSUE THREAD

**Issue by masq6r** [slaveOftime/Fun.Blazor#61]
`adaptiview` CE is really a brilliant idea and I found it very handy building dynamic pages. The CE's `Bind` implementation seems not support `cset`, `aset`, `alist` etc. Is there a plan to support them?

**Comment by albertwoo** [comment]
@masq6r thanks, I will explorer this use cases and see what I can do.

**Comment by masq6r** [comment]
I'm not so sure but maybe something like `adaptlist`, `adaptmap`?

**Comment by albertwoo** [comment]
We can make adaptiview to support alist or aset like:

```fsharp
adaptiview () {
            let! ls = AList.ofArray [| 1; 2 |]
            let! set = ASet.ofArray [| 1; 2 |]
            for x in ls do html.text x
            for x in set do html.text x
}
```

But not sure if **adaptlist**, **adaptmap** is needed. Because blazor has its own diff algorithm, the *adaptiview* is just to help ito make the scope smaller. Not sure how to integrate alist and aset with blazor diff more deeper.

**Comment by albertwoo** [comment]
Implemented https://github.com/slaveOftime/Fun.Blazor/pull/62
