### ISSUE TITLE
MudBlazorDemo.Client Fails

### ISSUE THREAD

**Issue by dxmas** [slaveOftime/Fun.Blazor#63]
MudBlazorDemo works great but MudBlazorDemo.Client fails with a 404 error.  Both are unchanged, I just cloned the repo.  What am I missing?

**Comment by albertwoo** [comment]
For **FunBlazor.MudBlazorDemo**, the **FunBlazor.MudBlazorDemo.Client** is just a project referenced by the server project, so it is not meant to be started directly. It's existing is just to demostrate you can create component or page in WASM mode and load or reload in WASM mode later from the server project.

**Comment by dxmas** [comment]
Thanks, obviously I have a few concepts to clarify for myself.
