### ISSUE TITLE
How to disable prerender?

### ISSUE THREAD

**Issue by masq6r** [slaveOftime/Fun.Blazor#64]
I'd like to disable prerendering feature for a Blazor component, how can I do it? `html.blazor` accepts a render mode parameter but no prerendering flag.

**Comment by albertwoo** [comment]
The renderMode is IComponentRenderMode, so if you are using server side render you should be able to create so it like: InteractiveServerRenderMode(prerender = false)

**Comment by masq6r** [comment]
Ah thanks... Didn't check the signature and realise that's IComponentRenderMode.
