### ISSUE TITLE
404 docs link on web page

### ISSUE THREAD

**Issue by NatElkins** [slaveOftime/Fun.Blazor#66]
This docs link:

<img width="286" alt="image" src="https://github.com/user-attachments/assets/22c2c426-80bf-41f5-81c8-3a5e364ce92c">

Goes here: 

<img width="976" alt="image" src="https://github.com/user-attachments/assets/bbc3cc5e-61d4-4c27-8cd7-0606cd5e4424">

Instead of here:

<img width="959" alt="image" src="https://github.com/user-attachments/assets/b804a2c4-b067-4b54-b742-f9c09fe6f011">

**Comment by albertwoo** [comment]
Yes, this is known issue, I am currently working on the beta version of it.
